### ISSUE TITLE
Image URL is Broken

### ISSUE THREAD

**Issue by aryasoni98** [cncf/tag-app-delivery#380] opened 2023-04-16 21:15 UTC
Example [https://github.com/cncf/tag-app-delivery/blob/main/website/content/_index.md](https://github.com/cncf/tag-app-delivery/blob/main/website/content/_index.md)

<img width="1252" alt="Screenshot 2023-04-17 at 2 30 21 AM" src="https://user-images.githubusercontent.com/18515597/232342536-5274b19b-ec7c-4a1c-a9b9-69f4d4826345.png">

**Comment by joshgav** [comment] 2023-10-16 17:40
This is the intended behavior as I noted above, cause the images render properly in the actual site. It would nevertheless be nice to fix this so images render in the raw files in GitHub too. If someone figures out how to achieve that please open a new issue and PR and help us out; in the meantime let's close this issue.

**Closed by joshgav** 2023-10-16 17:40 UTC
Labels: operators, website
